ungrouped:
  hosts:
    # No hosts are specified under ungrouped in this configuration

app_group:
  hosts:
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2223 # Port mapped for SSH in Docker Compose for app-1
      ansible_user: root
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224 # Port mapped for SSH in Docker Compose for app-2
      ansible_user: root
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225 # Port mapped for SSH in Docker Compose for app-3
      ansible_user: root
# load_balancer_group:
#   hosts:
#     managedhost-loadbalancer:
#       ansible_host: 0.0.0.0
#       ansible_connection: ssh
#       ansible_port: 2226
#       ansible_user: root
#       ansible_ssh_private_key_file: ./secrets/
